import * as brotli from 'brotli';
import {promisify} from 'util';
import {ArgumentParser} from 'argparse';
import * as fs from 'fs';

const readFilePromise = promisify(fs.readFile);
const writeFilePromise = promisify(fs.writeFile);

const parser = new ArgumentParser({
  description: "Bundle files as base64 into a single TypeScript file.",
});

parser.addArgument(['-o', '--output'], {
  action: 'store',
  required: true,
  help: 'The output path for the typescript bundle',
});

parser.addArgument('file', {
  help: 'The file to bundle as base64',
});

async function main() {
  const args = parser.parseArgs();
  const path = args.file as string;
  const buffer = await readFilePromise(path);
  console.log(buffer);
  const compressed = Buffer.from(brotli.compress(buffer, {mode: 0}));
  const base64 = compressed.toString('base64');

  // Code generation
  const sourcecode = `// This file is generated by tfjs/tools/base64_bundle.ts
// (likely by //tools:base64_bundle.bzl).
import {decompress} from 'brotli';

const compressedBase64 = ${JSON.stringify(base64)};
const compressedByteString = atob(compressedBase64);
const compressed = Uint8Array.from(compressedByteString, c => c.charCodeAt(0));
export const data = decompress(compressed as Buffer);
`;
 
  writeFilePromise(args.output, sourcecode);
}

main();
